### ISSUE TITLE
System.ExecutionEngineException causes immediate exit rather than break when debugging

### ISSUE THREAD

**Issue by mitchcapper** [dnSpyEx/dnSpy#104]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
 0a947e48801cb3f835c1a524b669e7d5fa457501

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I am not sure how to reproduce execution exceptions reliably, given it is a engine failure.  When it happens though dnSpy will terminate instantly rather than breaking.
The output shows
```
02:41:25.932 An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.dll
02:41:25.935 Additional information: "<no exception message>"
```
Confirmed it is checked under break when thrown.  The same exception in VS does pause and have a callstack.

**Comment by ElektroKill** [comment]
Hi, dnSpy is able to catch an `ExecutionEngineException` if it is thrown from the user code. However, usually, this exception is thrown by the CLR whenever it detects that something has gone horribly wrong. This exception does not always get thrown at the exact time something went wrong but rather when the CLR realizes that something is up and it's time to stop to prevent further unexpected behavior. These exceptions are often uncatchable since they indicate that something is very wrong and execution has to be stopped immediately. This straight however does not apply to `ExecutionEngineException` thrown using the `throw` CIL OpCode generated by `throw X;` C# expressions. In these cases, dnSpy can catch them.
![image](https://user-images.githubusercontent.com/37494960/179370070-ad4bb24d-73bf-495d-817e-e0d816c0b6b3.png)

Looking at the output provided it looks like the exception that is thrown when debugging in dnSpy is in fact coming from the internals of the CLR as `System.Private.CoreLib.dll` does not have any usages of `ExecutionEngineException` in the method bodies.

In order to properly resolve this, the following is needed:
Are you sure the exception that VS is catching is being thrown by the CLR itself and not by a `throw` statement?
Are you able to provide a file that can reliably cause the CLR to throw the exception? (I know this may be hard due to the nature of this exception and when it occurs)

**Comment by mitchcapper** [comment]
And closing this as idiot.  I thought it was doing a clean VM deploy but the dnSpy settings were persisting and "Ignore Unhandled Exceptions" was checked. Sadly didn't notice until another setting persisted.
