### ISSUE TITLE
Lacking "../dnSpyFiles/dnSpy.c" in mono patcher project

### ISSUE THREAD

**Issue by xhsu** [dnSpyEx/dnSpy#127]
- What version did you use?
Try to make it work on 2019.4.30f1, on the RimWorld

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Follow all the steps, until the file "dnSpy-Unity-mono-v2019.x-V40.sln" no found. Thus I put a dummy renamed txt file to replace it and successfully gets my hands on the project.
However, there's a compiler error saying the file "../dnSpyFiles/dnSpy.c" cannot be included.
I searched basically the entire internet and have to conclude that this file is nowhere to be found, and it is necessary for the C language linker.
Could someone kindly offer it?

**Comment by ElektroKill** [comment]
Hi, `dnSpy-Unity-mono-v2019.x-V40.sln` and `dnSpyFiles/dnSpy.c` both exist in the `dnSpy` branch. Please reread the instructions in the README.md file in the https://github.com/dnSpyEx/dnSpy-Unity-mono repository if you are looking into submitting a new patched Unity Mono version! It covers all the steps necessary in order to complete the process properly and without errors!

**Comment by ElektroKill** [comment]
Closing due to lack of response. I assume the question and problem faced has been resolved.
