### ISSUE TITLE
How to recompile from the command line? 

### ISSUE THREAD

**Issue by ExtremeGTX** [dnSpyEx/dnSpy#130]
Thanks for providing such great tool. 

Version: 6.2.0.0 (latest from CI #203)

I'm working on translating a tool written in c# and wanted to automate the translation, by decompile -> patch -> recompile. 

is it possible after decompiling and patching the classes to recompile again and generate an exe?

that works flawlessly from GUI, but is not efficient since a lot of strings needs to be translated.

Thanks in advance

**Comment by ElektroKill** [comment]
Hi, dnSpy command line does not currently support assembly editing and it would be a huge pain to implement support for it as the assembly editing logic is completely separate from the command line and UI and is implemented in the form of an extension loaded by the main UI process. For your use case, I suggest translating the strings on the CIL instruction level as it does not need decompilation and recompilation which can occasionally cause behavior changes due to decompilation not being 100% accurate in every case. This can be achieved using a metadata editing library like dnlib which will allow you to read the instruction stream from a .NET module, change the strings, and then save the module back to disk without needing a decompiler and a compiler. This is a far more efficient and far more scalable approach. It does need one to get accustomed to the CIL instructions a bit.

**Comment by ExtremeGTX** [comment]
Thanks for explanation and suggesting an alternative.
Will try to implement a solution based on your suggestion.
