### ISSUE TITLE
Can't decompile obfuscated file

### ISSUE THREAD

**Issue by beastdrc** [dnSpyEx/dnSpy#131]
Trying to decompile obfuscated file. 
There is no question to about deobfuscation, but it's the decompilation error
even it deobfusacted with de4dot, got same error
Attached screenshots and files. 

![Clipboard01](https://user-images.githubusercontent.com/38570368/188274158-c17c82bb-0d97-4934-916b-77958a7e057a.jpg)
![Clipboard02](https://user-images.githubusercontent.com/38570368/188274161-47bea50e-3fe5-4b00-8423-0d37e33fbedb.jpg)
[files.zip](https://github.com/dnSpyEx/dnSpy/files/9482745/files.zip)

**Comment by GazziFX** [comment]
Make breakpoint after first call in `<Module>.cctor` and dump module
![image](https://user-images.githubusercontent.com/43498426/188276705-286c8069-ef07-4daf-87a2-e77512eec03a.png)
Also check youtube https://youtu.be/biUbaBKvFV0

**Comment by ElektroKill** [comment]
Hi, the reason for the decompilation failing is that most of the method bodies in that module are encrypted and contain invalid IL code.
![image](https://user-images.githubusercontent.com/37494960/188280143-74f27b9f-9e28-4016-adc3-e791f320471f.png)
There is no way to decompile the code shown above into any form of C# code as its just completely invalid.

In order to decompile the methods in this module you need to either decrypt the method bodies or dump the module like @GazziFX mentioned.

I am closing this issue as there is nothing I can do to make the crash not appear!
