### ISSUE TITLE
Hide this keyword when decompiling.

### ISSUE THREAD

**Issue by gir489returns** [dnSpyEx/dnSpy#201]
### Problem Description

The decompiler will show you the this keyword constantly when referring to members/functions used within the class. However, this is unnecessary and extraneous. Generally only the super keyword is needed to be displayed as that is a special scenario when the inheritance model is broken. 

### Proposal

Add a configuration flag in View -> Options -> Decompiler to hide the this keyword.

**Comment by ElektroKill** [comment]
Hi, this is because the current decompiler does not implement any sort of member resolution on the C# level. The old ILSpy 2.4 decompiler engine used by dnSpy always qualifies the members with `this` or the current static type name even if it is not necessary as it does not have any knowledge of when or when not the qualification is needed. More modern decompilers, like ILSpy 8, implement additional analysis based on the C# member resolution spec to figure out if `this` or `base`, etc. is necessary in a given context. Implementing this complicated analysis in the old decompiler engine is truly not worth the effort. 

This will be fixed when dnSpy eventually moves to the ILSpy 8 decompiler engine. For progress please see issue #5 and the https://github.com/dnSpyEx/dnSpy/tree/feature/new-ilspy branch (this branch is not yet stable so I don't recommend it for daily use). I have a lot of local changes ready to be pushed to make it more stable but I haven't gotten around to finalizing them yet and merging in the latest stable release of ILSpy 8.

I will close this issue and progress on this matter will instead be tracked in the aforementioned issue.
