### ISSUE TITLE
.resx not create properly

### ISSUE THREAD

**Issue by manojdjoshi** [dnSpyEx/dnSpy#207]
### Description

missing resource data in resx please check

**Comment by ElektroKill** [comment]
Hello, Please provide me with the steps to reproduce the issue you are reporting. Without any additional information and way to reproduce I cannot fix it. Since this is a decompilation issue, please provide a file which can be used to reproduce the issue. Furthermore, next time when reporting a bug please use and fill in the correct bug report template. If no further information is provided I will be forced to close the issue!

**Comment by manojdjoshi** [comment]
please check this 
[https://drive.google.com/file/d/1lPCQPsH2ZxWjbSV6FlalVXnnlMMdnOAh/view?usp=sharing](url)

create resx file with decompile 

![](https://img001.prntscr.com/file/img001/HJhwWRjaRmKLxNdlYsg4cQ.png)

open solution in visual studio then open resx file error because resx file not have resources(image or string) data

![](https://img001.prntscr.com/file/img001/jHXKBaTWQb-q9ghAnNOhXA.png)

if we decompile without resx then convert .resources file to .resx with Resgen. created resx perfect converted by Resgen
