### ISSUE TITLE
Preserve all PE sections

### ISSUE THREAD

**Issue by unrealsecurity** [dnSpyEx/dnSpy#209]
### Problem Description

dnSpy doesn't preserve custom PE sections when saving a module. While it's not very common in .NET executables; software, including malware, will store data in custom PE sections.

### Proposal

Preserve original PE sections ¯\\\_(ツ)\_/¯

**Comment by ElektroKill** [comment]
Hello, have you tried enabling the `Mixed-Mode Module` option when writing the file? Enabling it should make dnSpy reuse the original PE for the new metadata instead of building one from scratch which in turn should preserve any additional or modified PE sections.
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/4e228df2-2415-47f6-935e-1b116cd77bd4)

**Comment by unrealsecurity** [comment]
I'll try this this now. Thank you!

**Comment by unrealsecurity** [comment]
Okay, that does the trick. I learned something new about dnSpy today. 

Thank you again and I'll close this issue now.
