### ISSUE TITLE
CS1056	Unexpected character '\u4DDB'

### ISSUE THREAD

**Issue by billpeace** [dnSpyEx/dnSpy#219]
### Problem Description

internal partial class spr\u4DDB
{
         public static byte[] 訣 = new byte[]
	{}
}

	CS1056	Unexpected character '\u4DDB'	main.g.cs	5

### Proposal

how to modify？

**Comment by GazziFX** [comment]
use de4dot, then modify

**Comment by ElektroKill** [comment]
This error is caused by the fact that you are trying to compile code that contains obfuscated member names that are not valid C# identifiers. If you wish to edit the method you have two choices:
* Edit the underlying IL code using the `Edit IL Instructions` option in the right-click context menu
* Deobfuscate the file using a tool that will rename the members to names that are valid C# identifiers. As mentioned by @GazziFX this can be achieved using `de4dot`.

Nothing can be done to make these identifiers compile as the C# compiler has strict rules on what characters are valid in symbol names.
