### ISSUE TITLE
Is it normal to fail to save the module after opening an obfuscated Net program?

### ISSUE THREAD

**Issue by XiaoYingYo** [dnSpyEx/dnSpy#221]
### dnSpyEx version

dnSpy v6.4.0 (64-bit, .NET, Admin)

### Describe the Bug

![image](https://github.com/dnSpyEx/dnSpy/assets/54934866/ad3d68c3-1fc9-468f-a032-c22f6217ca6b)
Program download Url:[https://drive.google.com/file/d/153sePrzlwVGDX8e4FxOfCuCOhRMvi0Gj/view?usp=sharing](https://drive.google.com/file/d/153sePrzlwVGDX8e4FxOfCuCOhRMvi0Gj/view?usp=sharing)

### How To Reproduce

Put the program I uploaded into dnspy to decompile, even without any modification, I can't save the exe to the executable file

### Expected Behavior

Even without any modification, it should be able to be saved as an executable file.exe

### Actual Behavior

Unable to save .exe as executable

**Comment by GazziFX** [comment]
It produces warnings but still saves file as expected

**Comment by XiaoYingYo** [comment]
> It produces warnings but still saves file as expected

But it can't run anymore, it seems to be the failed file

**Comment by ElektroKill** [comment]
As @GazziFX mentioned, dnSpy still writes the file to disk as best as it can.

There are many reasons as to why the file may not run. The file you are trying to save is heavily obfuscated and there is a high chance that it employs some anti-tampering measures in order to prevent editing. The best thing to do would be to deobfuscate the file first before attempting to edit it. However, if you cannot for some reason deobfuscate the file, you can try to customize the writer options to tell dnSpy to try to preserve as much of the original data as possible when writing the module to disk.

These options can be found in the `MD writer options` tab in the Save Module dialog. If you want to preserve as much as possible from the original file, please enable every option in that tab. If enabling all these options does not work, you might be out of luck and the only way to edit the module without breaking it would be to first deobfuscate it.

**Comment by GazziFX** [comment]
Maybe it has hash check or its problem with underlying library - dnlib

**Comment by XiaoYingYo** [comment]
> As @GazziFX mentioned, dnSpy still writes the file to disk as best as it can.
> 
> There are many reasons as to why the file may not run. The file you are trying to save is heavily obfuscated and there is a high chance that it employs some anti-tampering measures in order to prevent editing. The best thing to do would be to deobfuscate the file first before attempting to edit it. However, if you cannot for some reason deobfuscate the file, you can try to customize the writer options to tell dnSpy to try to preserve as much of the original data as possible when writing the module to disk.
> 
> These options can be found in the `MD writer options` tab in the Save Module dialog. If you want to preserve as much as possible from the original file, please enable every option in that tab. If enabling all these options does not work, you might be out of luck and the only way to edit the module without breaking it would be to first deobfuscate it.

thank you for your reply

**Comment by XiaoYingYo** [comment]
> Maybe it has hash check or its problem with underlying library - dnlib

thank you for your reply
