### ISSUE TITLE
Save assembly exception: Target instruction is too far away for a short branch

### ISSUE THREAD

**Issue by wuhensoft** [dnSpyEx/dnSpy#225]
### dnSpyEx version

6.4.0

### Describe the Bug

A very huge class about 100000 lines code,when i modify some functions with IL code and save the assembly, error occurs:
```
Target instruction is too far away for a short branch. Use the long branch or call CilBody.SimplifyBranches() and CilBody.OptimizeBranches(). Error occurred after metadata event BeginWriteMethodBodies during writing method  xxx
```
I did some research in google,and found the exception is in dnlib:
[dnlib source code](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/MethodBodyWriterBase.cs)

Line 363:
```
		/// <summary>
		/// Writes a <see cref="OperandType.ShortInlineBrTarget"/> operand
		/// </summary>
		/// <param name="writer">Instruction writer</param>
		/// <param name="instr">Instruction</param>
		protected virtual void WriteShortInlineBrTarget(ref ArrayWriter writer, Instruction instr) {
			int displ = (int)(GetOffset(instr.Operand as Instruction) - (ToInstructionOffset(ref writer) + 1));
			if (sbyte.MinValue <= displ && displ <= sbyte.MaxValue)
				writer.WriteSByte((sbyte)displ);
			else {
				Error("Target instruction is too far away for a short branch. Use the long branch or call CilBody.SimplifyBranches() and CilBody.OptimizeBranches()");
				writer.WriteByte(0);
			}
		}
```

It this a bug for dnspy or not,  I am not sure.

### How To Reproduce

1. Open a assembly contains a class  with 100k lines code
2. Modify a function with IL code, for example: add save file instruction 
```
File.WriteAllBytes("jg.pdf", buff);
```
3. File - Save Module - OK button
4. After save done,error occurs:
```
正在写入 C:\Users\Administrator\Desktop\Debug\xxx.dll...
Target instruction is too far away for a short branch. Use the long branch or call CilBody.SimplifyBranches() and CilBody.OptimizeBranches(). Error occurred after metadata event BeginWriteMethodBodies during writing method 'System.Void xxx::xxxx(System.String,xxxx,System.Boolean)' (0x0600xxxx).
所有文件已保存。

```

### Expected Behavior

Save the assembly successfully

### Actual Behavior

Exception occurs.

**Comment by GazziFX** [comment]
If your target branch is more than 32k instructions away then you need to use branch without `.s` suffix

**Comment by GazziFX** [comment]
I think checkbox "Recalculate branches" maybe added to IL editor, which just calls `SimplifyBranches`, `OptimizeBranches`

**Comment by ElektroKill** [comment]
Hi,

This is an intended error message designed to tell you that the CIL body of a method is invalid. This is probably caused by the fact that the original IL body used a short branch (identified by `.s` suffix e.g. `br.s`) (a short branch has a limited displacement in the range of -128 to 127 bytes). When you inserted additional instructions to the CIL body using the editor, it is highly likely that at least one of the target instructions of a short branch got moved further away from the short branch and the necessary displacement is too high to fit in the short branch.

In order to fix this you would need to identify the short branch in this CIL body that is causing the issue and change the opcode of that instruction to the long form of the branch.



> I think checkbox "Recalculate branches" maybe added to IL editor, which just calls `SimplifyBranches`, `OptimizeBranches`

These options already exist in the context menu!
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/2ada8b3d-7b75-43d3-9329-f4c2bcd92285)

**Comment by wuhensoft** [comment]
> 

got it!! thanks very much!
