### ISSUE TITLE
Save for memory modules are not identical to what is in memory

### ISSUE THREAD

**Issue by mitchcapper** [dnSpyEx/dnSpy#235]
### dnSpyEx version

3de5a55

### Describe the Bug

If you use the modules window to save a module from memory it is not identical to the disk version nor the version in memory.

It can result is modules that refuse to load with things like "not a valid Win32 application".   Sometimes the differences are minor, but sometimes I can see 10KB+ size differences (generally that is just trimmed from the end).   I am assuming it is exporting the module through dnlib exporter rather than saving bytes from memory.

I tried loading the module from memory in dnspy and doing the save module and manually preserving all the features with similar issue.

Here is an example of the difference between the on disk file and the exported from the modules window file:
![image](https://github.com/dnSpyEx/dnSpy/assets/1643324/35e5b7e7-e18f-4eca-86c1-2712436d4257)

Oddly if you inspect the memory directly in dnspy from the module window it is the same as the on disk:
![image](https://github.com/dnSpyEx/dnSpy/assets/1643324/bd92429c-3208-410f-85e3-7b75aea53b88)
(notice after the 44 00 00 42 highlighted on disk/in memory are all 0's but the exported has that line removed).

### How To Reproduce

Run the attached project, export nlog.dll from the module window with the debugger attached,  compare to file on disk
[ConsoleApp37.zip](https://github.com/dnSpyEx/dnSpy/files/12406531/ConsoleApp37.zip)

### Expected Behavior

they match

### Actual Behavior

are different.

### Additional Context

while yes just directly copying a module from disk is silly through save module, for memory only modules it makes more sense.  Assuming it is 100% the same in memory I could do a PR to "save module bytes from memory" or similar to try and get a more exacting copy.

**Comment by ElektroKill** [comment]
> I am assuming it is exporting the module through dnlib exporter rather than saving bytes from memory.

The `Save Module` feature does not use dnlib to read or write modules. It reads the content from memory and if the file is memory mapped it also fixes up the positions of the data sections to match what is expected for files. You can see the code here:
https://github.com/dnSpyEx/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger/ToolWindows/Modules/PEFilesSaver.cs#L75
The differences you are observing could be from this conversion from mapped layout to file layout. These conversions cannot be omitted as when a file is loaded into memory the data sections can be positioned differently and have different length. (Differences between `VirtualAddress` and `PointerToRawData` and also `VirtualSize` and `SizeOfRawData`)

If these fixups are omitted we get a dump which is pretty much broken as the offsets to section data no longer point to the correct data: (top is without fixups for memory mapped files, bottom is with fixups)
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/e47daf75-bb45-410c-80fb-e2dbbf602a29)
The fixups are necessary if we want to ensure the dumped file works.

The differences you are seeing at the start of the file are all part of the `IMAGE_OPTIONAL_HEADER` structure. The original file contains the 32bit version of the optional header while the dumped version contains the 64bit version. This might seem odd at first glance but it if we consider how .NET images (especially those with AnyCPU target architectures) work it makes sense. The original file is AnyCPU (64-bit preferred) and due to this it must contain the 32bit optional header to work on 32bit systems. In order to allow 64bit support, the runtime will rewrite the header to the 64bit variant when the file is being loaded in a 64bit context (which is what happens when `NLog.dll` is loaded by `ConsoleApp37.exe`. The actual values stored in the header are the same but the differences appear due to some properties being omitted in the 64bit header (like `BaseOfData`).

I'm not entirely decided whether the optional header should be left as is in the file when dumped or if perhaps some additional logic should be implemented to rewrite the the optional header back to the 32bit variant for maximum functionality of these AnyCPU files when saved from memory.

Hope this answers some  of your questions regarding the differences you observed!

**Comment by mitchcapper** [comment]
Thank you for the detailed description and sorry for the lazy bug reporting I should have dug into the code more first.   I actually pulled the dlls using a different application that uses dnlib for at least some parts so I assumed dnSpy likely operated similarly as I found the same result when doing it manually in dnspy.     I put together some automated 010 editor templates when doing some unmanaged .net mapping and noticed potentially similar behavior.  For the PEB headers for example it had both a 64 bit and 32 bit versions loaded in memory for 32 bit executables nearly identical sections but different actual functional target blocks in terms of what would work for accessing the data beyond the headers like the LDR table entries.

In looking at the bigger data loss it looks like the few minor bytes in the header with the size/initial offset etc:
![image](https://github.com/dnSpyEx/dnSpy/assets/1643324/848fb473-8cca-474a-aa99-6f9f11741a5c)

nearly the rest of the entire file is the same except at the end the windows certificate, reloctable, and debug directory:
![image](https://github.com/dnSpyEx/dnSpy/assets/1643324/66a2624f-2509-4152-bc96-beaf404d3fd7)

are all stripped off.  I don't see the certificate initially in memory though so that may not be ever loaded in.

**Comment by GazziFX** [comment]
Probably because cert in overlay and not included in PE size

**Comment by GazziFX** [comment]
I will recommend to set breakpoint on Assembly.Load and save bytes

**Comment by mitchcapper** [comment]
Sure, and honestly not currently causing an issue for me on anything just a difference I noticed.  There are relatively few differences in the main headers between the originals and the exported one: https://page2.dnspexport.workers.dev/Report .  I wonder if it is worth switching it back to the 32 bit header.  Might not solve all load issues but happy to give it a shot if it seems worthwhile.

**Comment by ElektroKill** [comment]
Hi, I've looked into this further and I concluded that rewriting the optional header is not something that should be done as some of the data required to do that is no longer available. The most important is the AddressOfEntrypoint field being changed to a value of `0x200` compared to the previous value of `0xCD3E2`. The reason for the change is that this value is no longer necessary as 64-bit .NET images do not need a native entry point to be present as compared to 32-bit .NET images which require a native entry that jumps to the CLR. This is part of the conversion done by the runtime when loading an AnyCPU compiled binary in a 64-bit context. The relocation table is also removed as probably the only entry there is to allow this unmanaged entry point to work even if the image is loaded at a different base address.

Currently, the images saved from memory should work but AnyCPU capabilities will be lost due to the optional header being rewritten by the CLR and some of the crucial information being removed. Rewriting this header back to the 32-bit header would break the files unless more work is done to restore the entry point and base relocation directories to allow the 32-bit header to be rebuilt completely. While this is probably possible, I think this is out of the scope of dnSpy and should be done by the end-user if they deem it necessary. Making sure the dumped images are identical to the original on-disk images in all cases is far from easy and fixing some things but not fixing others will be confusing to the end-user.

As for the missing certificate and debug, this information is probably not loaded into memory when the image is loaded for execution or the references to it are removed from the optional header when the runtime rewrites it to the one for the given context in which the AnyCPU image is loaded. However, I'm not sure about this.

If you have any further questions please ask or otherwise close the issue :D
