### ISSUE TITLE
macOS .NET core debugging

### ISSUE THREAD

**Issue by ventsislav-georgiev** [dnSpyEx/dnSpy#238]
### Problem Description

Is it possible to build and run dnSpy on macOS and use it for debugging .NET core apps on mac?
If so, what are the requirements/limitations in doing so?

### Proposal

There is https://avaloniaui.net/XPF for porting WPF to macOS. Or refactoring for https://avaloniaui.net for cross-platform GUI.

**Comment by ElektroKill** [comment]
> Is it possible to build and run dnSpy on macOS and use it for debugging .NET core apps on mac? If so, what are the requirements/limitations in doing so?

Currently, it is not possible to run dnSpy on macOS natively. dnSpy is written with Windows in mind and uses WPF which is not a cross-platform UI framework thus any app written with it will not run natively on any OS besides Windows. It is, however, possible to compile the Windows version of dnSpy on macOS. It is also theoretically possible to run the Windows build of dnSpy on macOS using compatibility layers like Wine or virtualization tools like Parallels. However, doing so will most likely not allow the debugger component to function correctly. I can't state how well it works using such workarounds since I do not own a macOS system. 

> There is [avaloniaui.net/XPF](https://avaloniaui.net/XPF) for porting WPF to macOS. Or refactoring for [avaloniaui.net](https://avaloniaui.net) for cross-platform GUI.

I'm well aware of both Avalonia and their XPF product. In the case of dnSpy, XPF is not an option due to it being targeted at commercial applications willing to pay up for usage of XPF to migrate their software and several unsupported WPF features they mention on their website are used in dnSpy. As for a full-on port from WPF to Avalonia, this is a massive undertaking and I don't really have the time and motivation to go through porting and rewriting the majority of the UI code to use Avalonia as the UI framework.

I know macOS/Linux support is something that many people would like but I currently do not have the facilities to go through the process of porting such a large project to Avalonia.

Hope this answers your questions!

**Comment by ventsislav-georgiev** [comment]
Thank you for the detailed explanation! The effort isn't worth it yet. Even with .NET core supporting cross platform builds still most .NET apps are written in Windows.

Now with MS pushing the cross platform .NET development environment in VSCode with the [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit), we may see a proper change in that regard and who knows, MS may try to tackle the WPF cross-platform support themselves (buying Avalonia, improving it and offering it for free :smile:).
