### ISSUE TITLE
After getting error in "Save Module" perhaps the error puffer is not reset.

### ISSUE THREAD

**Issue by FickoDeLux** [dnSpyEx/dnSpy#258]
### dnSpyEx version

6.4.1

### Describe the Bug

After deleting a property, which is still referenced somewhere in the modul the "Save Module" action run on error.
That's expected.

But reverting the changes. (Puting the deleted property back) not remedy the situation.
Still producing the same error by "Save Module".

The module somehow will not be refreshed to the good state after producing an error.

### How To Reproduce

Delete a property, which is still referenced. (Decompile a class, delete a public property referenced somewhere else, recompile it.)
Do "Save Module". (Should get error)

Decompile the same class, put the property back, recompile.
Do "Save Module". (Still get error)

### Expected Behavior

Not get an error after reverting the mistake.

### Actual Behavior

Getting the same error.

**Comment by ElektroKill** [comment]
Hi, if you removed a property and then added it back using the C# editor or using the Add Property context menu option it will not work since that does not adjust the references to the property. The only way to undo a property deletion is to use the undo feature in dnSpy.

The reason for this is the representation of references to properties on the dnlib object model. Method bodies contain references to the MethodDef objects for the property accessors and when you delete a property these MethodDef objects get deleted from the module invalidating all those references as the object they point to no longer is present in the module. When you add back the property using the C# editor or the Add Property context menu action, you create a brand new property object with a set of brand new MethodDef objects for the accessors. The references to the old property remain invalid and setting them back si not a viable option as there is no way of knowing whether its new property is meant to replace the old one or not.

Hope this clears things up!

**Comment by FickoDeLux** [comment]
That`s make sense.
Thank You.

**Comment by ElektroKill** [comment]
Good to know, I will go ahead and close the issue now!
