### ISSUE TITLE
Running under Wine (Linux)

### ISSUE THREAD

**Issue by FickoDeLux** [dnSpyEx/dnSpy#265]
### Problem Description

dnSpy v6.1.8 (x64) used to run under wine very nicely.
- Just had to copy "c:\Program Files\dotnet\" over the linux .wine  "c:\Program Files\dotnet\" to properly debug applications -

Something broke with the display - I guess because it seems to be running in the background but no GUI - using dnSpyEx.
I have a feeling that something trivial just can't put the finger on it,

### Proposal

May somebody have allready managed to get it work?
Or need some adjustment in the source?

**Comment by ElektroKill** [comment]
Hello, running dnSpy on any other operating system other than Windows is currently not officially supported. This is because of the usage of the Windows-only WPF UI framework. This lack of support includes Wine and other compatibility layers. I have seen people succeed at running dnSpy under Wine (they used Winetricks to install netframework4.8 and run dnSpy through Wine that way) but I have not tried it myself and cannot guarantee everything works smoothly. I also cant really pinpoint what could be going wrong on your end as I am not familiar with using Wine to any other compatibility layer on other operating systems. Something that might have been the cause is the update of the .NET runtime that dnSpy uses. dnSpy 6.1.8 ran on .NET 5 while the latest stable release of dnSpyEx (6.4.1) runs on .NET 6 and the latest CI builds run on .NET 8. As for eventual future native support for other operating systems, this is not something that I have the resources for. Porting such a big project to a completely different UI framework is a huge undertaking I just simply do not have the time and resources for :/

For some more insight into running dnSpy under compatibility layers and the problem of cross-platform UI ports, check out issue https://github.com/dnSpyEx/dnSpy/issues/222

I hope this answers your questions.
