### ISSUE TITLE
DnSpyEx under wine

### ISSUE THREAD

**Issue by sassywoocoo** [dnSpyEx/dnSpy#340]
### dnSpyEx version

6.5.1

### Describe the Bug

the GUI is very buggy deeming the software unusuable

### How To Reproduce

run under wine on linux

### Expected Behavior

actually running properly

### Actual Behavior

the gui keeps glitching and the buttons dont work

**Comment by ElektroKill** [comment]
Hello, there is really nothing I can do in this regard. WPF is designed by Microsoft to run on Windows. Wine is trying its best to bridge the gap between Linux and Windows. The GUI being buggy is most likely not dnSpy code (it works fine on Windows) but rather an issue with the Wine compatibility layer which I can do nothing about. I've heard of many people trying to run dnSpy under Wine and achieving various degrees of success.

If you know of something specific in WPF that causes problems on Wine that can be changed without impacting the UX on Windows, I'd be willing to look into it. However, without anything like this, there is really nothing I can do as the issue lies within the compatibility layer which allows you to run a Windows app on Linux.

As for making the app work natively on Linux, this would necessitate a complete rewrite of the UI code to a different UI framework, something which I have no time to do currently and existing translation layers for WPF -> different UI frameworks exist but are not designed for open source developers to utilize, for example, Avalonia XPF.

**Comment by SmallJoker** [comment]
For those who are wondering how to get dnSpy to run at all:

* Proton 9.0-2 via Steam does work
* wine-9.13 with dotnet48, dotnet40, DXVK (and also tried with WineD3D) does currently result in a very long error message (excerpt below).

![wine-9.13](https://github.com/user-attachments/assets/0cadbbd1-b434-409a-b37b-8a5837356bac)

Tested functionalities:

:ballot_box_with_check: Loading assembly with dependencies
:ballot_box_with_check: Assembly symbol searches
:ballot_box_with_check: IL code disassembler
:ballot_box_with_check: IL code patching
:ballot_box_with_check: Test of patched binary

If the system font is too small -> open `winecfg` by reconfiguring the launch executable of the newly created Steam library entry.

**Comment by NopeNopeGuy** [comment]
>     * wine-9.13 with dotnet48, dotnet40, DXVK (and also tried with WineD3D) does currently _NOT WORK_ and results in a very long error message

It does work, you probably didn't disable dxvk correctly because it seems to work just fine on a clean wineprefix with dotnet48

**Comment by dagriefaa** [comment]
i'll note that if it does boot via proton but popup menus and tooltips are black, using launch options `PROTON_USE_WINED3D=1 %command%` fixed that issue for me
