### ISSUE TITLE
Stuck forever decompiling on click to goto function

### ISSUE THREAD

**Issue by cspain** [dnSpyEx/dnSpy#352]
### dnSpyEx version

6.5.1 & latest passing

### Describe the Bug

Clicking on a function call to go to the code pops up the usual Decompiling overlay and instead of going away after a few seconds, it stays there indefinitely.
![image](https://github.com/user-attachments/assets/12531ab4-abb0-4aeb-95a4-c09383d38b6b)

### How To Reproduce

Open the file (I have not attached as it is the output from a piece of malware) and go to the entry point. Click on the function and watch the Decompiling window stay forever. I can manually go to the function via the left navigation pane.

### Expected Behavior

Decompiling overlay does not stay forever and we switch to the code for function clicked on.

### Actual Behavior

Decompiling window stays there forever:
![image](https://github.com/user-attachments/assets/505d484e-265b-42da-a9cd-dc71b836df36)

**Comment by zuoyuanchun** [comment]
According to the information in the picture you provided, the following information can be obtained:
1. This program is developed and compiled using VB .NET
2. This program uses an obfuscation tool for obfuscation
I suggest that you first use the "Detect_It_Easy" tool to determine the type of obfuscation tool, and then find the corresponding anti-obfuscation tool.
Because the purpose of the obfuscation tool is to prevent decompilation.
