### ISSUE TITLE
Installation using package managers

### ISSUE THREAD

**Issue by SupinePandora43** [dnSpyEx/dnSpy#47]
i would LOVE to see `dnSpyEx` appear in search results of `pamac-manager`, or at least, in AUR.

**Comment by ElektroKill** [comment]
Hi, I understand that by `AUR` you mean the Arch User Repository. If yes, then why should an application which only officially supports windows be available on Linux package managers. I'm a Linux newbie so if I'm missing something correct me ;)

**Comment by SupinePandora43** [comment]
It's windows only? :flushed:

**Comment by ElektroKill** [comment]
Yeah, windows only currently because the application relies on WPF which is a Windows framework. You can probably run it under Wine or a different compatibility layer but that's not supported and might not work.

**Comment by somebody1234** [comment]
@SupinePandora43 fwiw it'll work if you just download the normal (~26mb) zip and follow these instructions:
https://www.reddit.com/r/linux4noobs/comments/firqs9/getting_windows_wpf_applications_to_run_with_wine/

while i'd love it if it was available on the AUR, i don't think it's a good idea since it depends on both dotnet48 and a registry key being added... if you have a way to do it that follows the [packaging guidelines](https://wiki.archlinux.org/title/Wine_package_guidelines) though feel free to submit to the AUR yourself
