### ISSUE TITLE
Info on Support for New Win 11 context menu

### ISSUE THREAD

**Issue by Deltafox79** [dnSpyEx/dnSpy#62]
Hi, is it possible to implement dnspy on new windows 11 contex menu?

I know there are sources but only in c ++ here:

[https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages](https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages)

the only option possibly use a P / invok functions.?

Other possible source...

https://github.com/ikas-mc/ContextMenuForWindows11

Best Regards

**Comment by ElektroKill** [comment]
Hello, according to the resources you provided and some research I did on my own, it seems that in order to integrate with the new "modern" Windows 11 context menu a shell extension would have to be written. Shell extensions are usually written in an unmanaged language like C or C++ and require the usage of COM.
I have no idea why Microsoft decided to abandon the old method which used registry entries to modify the context menu and went with this overly complex approach.
Due to my limited knowledge of programming in languages like C++ and inability to test such a feature (my computer is not supported by Windows 11) I won't be adding support for the Windows 11 context menu. However, if you or someone else is willing to contribute and implement support for this I'm not against it.
