### ISSUE TITLE
Edit Code feature emits incorrect assembly references when editing a .NET Standard assembly

### ISSUE THREAD

**Issue by catester** [dnSpyEx/dnSpy#75]
In dnSpy v6.1.8 and v6.1.9, I was having a problem when editing and compiling a method in a .netstandard2.0 assembly which was using some Types from System.Drawing.Common. For future surfers here are the details:

```
Compiler Error CS0012
The type 'type' is defined in an assembly that is not referenced. You must add a reference to assembly 'assembly'.
```

Then after adding assembly reference to System.Drawing.Common.dll in "Edit Code" window, this time it was conflicting with System.Drawing.dll (the one from .NET Framework):

```
Compiler Error CS0433
The type 'type1 exists in both Assembly1 and Assembly2
```

Then I decided to clone this repository and compile with the latest commits and voila it worked! The "Edit Code" window compiled method body without any errors and even without adding assembly reference! Probably your commit 0436a8107922ba1722b1738d859eb210c519dfad fixed the issue, thank you very much!

Also a small suggestion: Maybe you should mention to use `dotnet build --configuration Release` or `dotnet build -c Release` in Readme.md because `dotnet build` builds Debug configuration by default. By the way I was able to build with downloading and installing  [.NET SDK 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), I didn't have Visual Studio 2022 on my machine (only 2019)

Also `dotnet clean` or `dotnet clean -c Debug` commands did not clean some DLLs in Debug bin and obj folders. I don't know if this is a limitation of dotnet command (maybe [this](https://github.com/dotnet/docs/issues/12304)) or if the projects have some custom DLL copy target but no target for Clean in msbuild. Fortunately I found the [dotnet-cleanup tool](https://sebnilsson.com/blog/dotnet-cleanup-clean-up-solution-project-folder/
) to handle the issue.

**Comment by catester** [comment]
Lol, I talked too soon. A second reference System.Drawing.Common, Version=6.0.0.0 is being added to the assembly (in addition to existing System.Drawing.Common, Version=4.0.0.1), along with System.Private.CoreLib. But this is a .netstandard2.0 assembly, not a .NET Core or .NET 6.0 assembly. It seems .netstandard2.0 is treated like .NET Core. I am trying to figure it out.

**Comment by ElektroKill** [comment]
Hi,
The issue here is that .NET Standard is not really a runtime but rather a standard. Due to this, there are only "reference assemblies" for .NET Standard, these assemblies do not contain any code and only contain the type, method, field, etc. signatures. There are no .NET Standard runtime assemblies, only .NET Core and .NET Framework. 

dnSpy always either resolves .NET Standard references to the .NET Corr or .NET Framework runtime assembly so that the "jump to reference" feature in dnSpy actually jumps to a method that contains code so that the user can inspect what a particular method does "under the hood". This sort of resolution causes issues as you underlined. The dnSpy "Edit Code" feature uses the official Roslyn compiler to compile the C# back to IL code which is stored inside the assembly. The compiler requires the consumer (in this case dnSpy) to provide all the assemblies that the code references. dnSpy provides the runtime assemblies from either .NET Core and .NET Framework as these are ones it resolves. The Roslyn compiler then generated code referencing these assemblies instead of the proper .NET Standard reference assemblies.

This issue is would be a hard one to fix as the assembly resolution logic would have to be modified to provide the reference assemblies for .NET Standard when editing the code but provide the .NET Core and .NET Framework runtime assemblies to the decompiler for "jump to reference to work".

I hope all that above-made sense and if you have any further questions make sure to ask :) 
I can not promise an ETA for a fix for this feature as it requires a lot of investigation into dnSpy internals and changing a lot of the assembly resolution.

**Comment by catester** [comment]
Thanks for the detailed explanation. I understand the issue now.

> This issue is would be a hard one to fix as the assembly resolution logic would have to be modified to provide the reference assemblies for .NET Standard when editing the code but provide the .NET Core and .NET Framework runtime assemblies to the decompiler for "jump to reference to work".

Yes, this should fix it. Note that dnSpy v6.1.8 at least allows you to edit methods that include mscorlib types without emitting new references but it is confused if there are uncommon types like from System.Drawing.Common.

Anyway, this is not urgent maybe we can have a solution in future.

**Comment by ElektroKill** [comment]
Hi,
I know it's been over a year since the last update on this matter, but can you please give the build available [here](https://github.com/dnSpyEx/dnSpy/actions/runs/4331101534) a go? I modified the assembly resolution logic for the compiler-based Edit commands to provide Roslyn with the reference assemblies instead of the runtime ones.
Please let me know of the results! If the problem you reported is solved then feel free to close the issue :p

**Comment by ElektroKill** [comment]
Closing as fixed due to lack of response.
