### ISSUE TITLE
cannot save settings

### ISSUE THREAD

**Issue by liesauer** [dnSpyEx/dnSpy#77]
- What version did you use?
[feature/new-ilspy](https://github.com/dnSpyEx/dnSpy/tree/feature/new-ilspy)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
change those settings doesn't work.
![image](https://user-images.githubusercontent.com/8676741/160231743-e4df7d3f-1ba9-4b27-9fbd-78620ac40ad4.png)

btw, dnSpy is not completely portable currently, the datas are stored into `%APPDATA%`, so there is a little problem when using multiple versions of dnSpy.

**Comment by ElektroKill** [comment]
Hi,
This is a known issue on the `feature/new-ilspy` branch due to that branch being heavily work in progress. Expect many more features like the debugger to not work on that branch. I'm currently slowly working on getting the decompiler to emit all the debug info dnSpy needs but it is quite a boring and tedious task. In general, I do not recommend using the  `feature/new-ilspy` as a daily driver for now as it is way too unstable for that.

As for the settings being in `%appdata%` folder, I don't think dnSpy was designed to be a portable application but I can't be sure as I am not the original developer of dnSpy.

**Comment by ElektroKill** [comment]
A update on the matter: Settings do now save on the latest version of the new decompiler branch, it was implemented together with the reworked decompiler settings screen!
