### ISSUE TITLE
Error to decompile some methods.

### ISSUE THREAD

**Issue by 0x2F0714** [dnSpyEx/dnSpy#92]
It's the same file on different versions of dnspy.

The dnSpyEx didn't decompile almost any method of the file.
The dnSpy version did it well.

You can see, the FileOffset of dnSpyEx is 0x00000000

dnSpyEx version: 6.2.0-rc1
dnSpy version: 6.1.7

![image](https://user-images.githubusercontent.com/77865776/174422876-62752947-8449-48b4-b27e-e5888a0dda19.png)

Here's the file.
[sr 3.0t.zip](https://github.com/dnSpyEx/dnSpy/files/8932936/sr.3.0t.zip)

**Comment by ElektroKill** [comment]
Hi, the cause of the issue is a change in the dnlib library which is used by dnSpy to read .NET metadata. Between versions 3.3.5 and 3.4.0 a change was made to the conversion between RVAs and raw file offsets. I will forward this bug to dnlib developers.

**Comment by 0x2F0714** [comment]
The file refuses to run cause you need the dependencies of the file run. But answering your question: yes. The file is obfuscated with vmp and I dumped the cil bodies.

![image](https://user-images.githubusercontent.com/77865776/174497973-a8990711-ce2b-4d11-85cf-405a62aca13b.png)

That's the sections of the obfuscated file without the bodies dumped.

**Comment by ElektroKill** [comment]
The application you uploaded fails to run with the following error message:
![image](https://user-images.githubusercontent.com/37494960/174588791-fef00f28-bc20-47ff-a365-63a70af9b8ca.png)
When .NET dependencies are missing the Common Language Runtime just throws a .NET Exception which leads to the program crashing. When running your file the Common Language Runtime is not loaded so it cannot be a dependency error.

I'm pretty sure the error is caused by the fact that the sections `.Rose` and `.vmp0` have `SizeOfRawData` set to 0 while having `VirtualSize` set to a number above 0 which leads me to believe that the section header information got corrupted during the dump or was perhaps purposefully sabotaged by, for example, an anti dump scheme.
![image](https://user-images.githubusercontent.com/37494960/174589368-1cf19c8c-30e2-4e95-a35d-cf76c9962379.png)

Could you perhaps attach the original file before a memory dump?

**Comment by 0x2F0714** [comment]
That's the original file.

[sr woofer 3.0.zip](https://github.com/dnSpyEx/dnSpy/files/8942662/sr.woofer.3.0.zip)

**Comment by ElektroKill** [comment]
This issue will not be fixed as dnSpy relies on dnlib to read the method bodies. If dnlib returns an empty body, this is what dnSpy will display. Furthermore, the assembly provided contains invalid metadata and does not execute properly. If you believe that dnlib should return full bodies in this case, please open an issue on the dnlib issue board linked below:
https://github.com/0xd4d/dnlib/issues
